auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Geyingqi
url: https://www.facebook.com/profile.php?id=100009276602565
feed: /atom.xml
author_info: <a href="https://www.facebook.com/profile.php?id=100009276602565">Geyingqi</a>
